package com.sporekart.ai.admin.domain;

public enum AdminOperationType {
    CONFIG_UPDATE, CONFIG_CREATE, CONFIG_DELETE, CONFIG_ROLLBACK,
    FEATURE_FLAG_CHANGE, MODULE_ENABLE, MODULE_DISABLE,
    ENVIRONMENT_SWITCH, IMPORT_EXPORT, MAINTENANCE_START, MAINTENANCE_END
}
