import { useMemo } from 'react';
import { MOCK_VARIANTS, MOCK_VARIANT_GROUPS } from '../mock/mockVariants';
import { MOCK_ATTRIBUTE_DEFINITIONS } from '../mock/mockAttributes';
import { MOCK_PACKAGING } from '../mock/mockPackaging';
import { MOCK_SKU_ENTRIES } from '../mock/mockSku';

export function useVariantAnalytics() {
  return useMemo(() => {
    const totalVariants = MOCK_VARIANTS.length;
    const activeVariants = MOCK_VARIANTS.filter((v) => v.status === 'active').length;
    const inactiveVariants = MOCK_VARIANTS.filter((v) => v.status === 'inactive').length;
    const draftVariants = MOCK_VARIANTS.filter((v) => v.status === 'draft').length;
    const archivedVariants = MOCK_VARIANTS.filter((v) => v.status === 'archived').length;
    const defaultVariants = MOCK_VARIANTS.filter((v) => v.isDefault).length;
    const variantGroups = MOCK_VARIANT_GROUPS.length;

    const totalAttributes = MOCK_ATTRIBUTE_DEFINITIONS.length;
    const filterableAttributes = MOCK_ATTRIBUTE_DEFINITIONS.filter((a) => a.filterable).length;
    const comparableAttributes = MOCK_ATTRIBUTE_DEFINITIONS.filter((a) => a.comparable).length;

    const totalPackaging = MOCK_PACKAGING.length;
    const primaryPackaging = MOCK_PACKAGING.filter((p) => p.isPrimary).length;
    const masterCartons = MOCK_PACKAGING.filter((p) => p.isMasterCarton).length;

    const totalSKU = MOCK_SKU_ENTRIES.length;
    const activeSKU = MOCK_SKU_ENTRIES.filter((s) => s.status === 'active').length;
    const autoGeneratedSKU = MOCK_SKU_ENTRIES.filter((s) => s.autoGenerated).length;
    const reservedSKU = MOCK_SKU_ENTRIES.filter((s) => s.reserved).length;
    const duplicateSKU = MOCK_SKU_ENTRIES.filter((s) => s.duplicate).length;

    const statusDistribution = [
      { status: 'active' as const, count: activeVariants, color: 'var(--color-accent-green)' },
      { status: 'inactive' as const, count: inactiveVariants, color: 'var(--color-accent-yellow)' },
      { status: 'draft' as const, count: draftVariants, color: 'var(--color-accent-orange)' },
      { status: 'archived' as const, count: archivedVariants, color: 'var(--color-accent-red)' },
    ];

    const groupDistribution = MOCK_VARIANT_GROUPS.map((g) => ({
      name: g.name,
      count: g.variants.length,
    }));

    return {
      totalVariants, activeVariants, inactiveVariants, draftVariants, archivedVariants,
      defaultVariants, variantGroups,
      totalAttributes, filterableAttributes, comparableAttributes,
      totalPackaging, primaryPackaging, masterCartons,
      totalSKU, activeSKU, autoGeneratedSKU, reservedSKU, duplicateSKU,
      statusDistribution, groupDistribution,
    };
  }, []);
}
