spring:
  devtools:
    restart:
      enabled: true
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/sporekart}
  jpa:
    show-sql: true
logging:
  level:
    root: DEBUG
