package com.sporekart.memory.domain;

public enum Source {
    CONVERSATION,
    SUPPORT_TICKET,
    PRODUCT_DISCUSSION,
    SALES_MEETING,
    TRAINING_HISTORY,
    INVENTORY_OBSERVATION,
    WAREHOUSE_ANOMALY,
    EXECUTIVE_NOTE,
    SUPPLIER_INTERACTION,
    PURCHASE_HISTORY,
    AGENT_OUTPUT,
    AI_REASONING,
    USER_PREFERENCE,
    CONTEXT_SUMMARY,
    KNOWLEDGE_LINK,
    SYSTEM
}
