import React from 'react';
import type { SKUEntry } from '../types';

interface SKUManagerProps {
  entries: SKUEntry[];
}

const section: React.CSSProperties = { padding: 'var(--space-component-gap)', display: 'flex', flexDirection: 'column', gap: 16 };
const table: React.CSSProperties = { width: '100%', borderCollapse: 'collapse', fontSize: 'var(--text-body-sm)' };
const th: React.CSSProperties = { textAlign: 'left', padding: '10px 12px', borderBottom: '2px solid var(--color-border)', color: 'var(--color-text-tertiary)', fontWeight: 600, textTransform: 'uppercase', fontSize: 'var(--text-body-xs)', letterSpacing: '0.5px', whiteSpace: 'nowrap' };
const td: React.CSSProperties = { padding: '10px 12px', borderBottom: '1px solid var(--color-border)', color: 'var(--color-text-primary)' };

export const SKUManager: React.FC<SKUManagerProps> = React.memo(({ entries }) => {
  return (
    <div style={section}>
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
        <h2 style={{ margin: 0, fontSize: 'var(--text-h2)', color: 'var(--color-text-primary)' }}>SKU Management</h2>
        <span style={{ fontSize: 'var(--text-body-xs)', color: 'var(--color-text-tertiary)' }}>
          {entries.filter((s) => s.duplicate).length > 0 && (
            <span style={{ color: 'var(--color-accent-red)', marginRight: 12 }}>
              ⚠ {entries.filter((s) => s.duplicate).length} duplicate{entries.filter((s) => s.duplicate).length > 1 ? 's' : ''}
            </span>
          )}
          {entries.filter((s) => s.reserved).length} reserved
        </span>
      </div>
      <div style={{ overflowX: 'auto', borderRadius: 'var(--radius-md)', border: '1px solid var(--color-border)' }}>
        <table style={table}>
          <thead>
            <tr>
              <th style={th}>SKU</th>
              <th style={th}>Variant</th>
              <th style={th}>Product</th>
              <th style={th}>Auto</th>
              <th style={th}>Reserved</th>
              <th style={th}>Duplicate</th>
              <th style={th}>Status</th>
            </tr>
          </thead>
          <tbody>
            {entries.map((s) => (
              <tr key={s.id} style={s.duplicate ? { background: 'var(--color-accent-red)08' } : s.reserved ? { background: 'var(--color-accent-orange)08' } : undefined}>
                <td style={{ ...td, fontFamily: 'monospace', fontWeight: 700, fontSize: 'var(--text-body-sm)' }}>{s.sku}</td>
                <td style={td}>{s.variantName}</td>
                <td style={td}>{s.productName || '-'}</td>
                <td style={td}>{s.autoGenerated ? <CheckIcon /> : '-'}</td>
                <td style={td}>{s.reserved ? <span style={{ color: 'var(--color-accent-orange)' }}>Reserved</span> : '-'}</td>
                <td style={td}>{s.duplicate ? <span style={{ color: 'var(--color-accent-red)', fontWeight: 600 }}>⚠ Duplicate</span> : '-'}</td>
                <td style={td}>
                  <span style={{
                    padding: '2px 8px', borderRadius: 10, fontSize: 'var(--text-body-xs)', fontWeight: 600,
                    background: s.status === 'active' ? 'var(--color-accent-green)20' : s.status === 'reserved' ? 'var(--color-accent-orange)20' : 'var(--color-bg-surface-raised)',
                    color: s.status === 'active' ? 'var(--color-accent-green)' : s.status === 'reserved' ? 'var(--color-accent-orange)' : 'var(--color-text-secondary)',
                  }}>{s.status}</span>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
});

function CheckIcon() {
  return <span style={{ color: 'var(--color-accent-green)' }}>✓</span>;
}
