import React from 'react';
import { useVariantAnalytics } from '../state/useVariantAnalytics';
import { MOCK_VARIANT_ACTIVITY } from '../mock/mockActivity';

const section: React.CSSProperties = { padding: 'var(--space-component-gap)', display: 'flex', flexDirection: 'column', gap: 24 };
const grid: React.CSSProperties = { display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(180px, 1fr))', gap: 12 };
const card: React.CSSProperties = { padding: 16, borderRadius: 'var(--radius-md)', border: '1px solid var(--color-border)', background: 'var(--color-bg-surface-default)', display: 'flex', flexDirection: 'column', gap: 4 };
const cl = { fontSize: 'var(--text-body-xs)', color: 'var(--color-text-tertiary)', textTransform: 'uppercase', letterSpacing: '0.5px' } as const;
const cv = { fontSize: 'var(--text-h3)', color: 'var(--color-text-primary)', fontWeight: 700 } as const;

export const VariantDashboard: React.FC = React.memo(() => {
  const a = useVariantAnalytics();
  return (
    <div style={section}>
      <h2 style={{ margin: 0, fontSize: 'var(--text-h2)', color: 'var(--color-text-primary)' }}>Variant Dashboard</h2>
      <div style={grid}>
        <div style={card}><span style={cl}>Total Variants</span><span style={cv}>{a.totalVariants}</span></div>
        <div style={card}><span style={cl}>Active</span><span style={cv}>{a.activeVariants}</span></div>
        <div style={card}><span style={cl}>Variant Groups</span><span style={cv}>{a.variantGroups}</span></div>
        <div style={card}><span style={cl}>Attributes</span><span style={cv}>{a.totalAttributes}</span></div>
        <div style={card}><span style={cl}>Packaging</span><span style={cv}>{a.totalPackaging}</span></div>
        <div style={card}><span style={cl}>SKU Entries</span><span style={cv}>{a.totalSKU}</span></div>
        <div style={card}><span style={cl}>Active SKU</span><span style={cv}>{a.activeSKU}</span></div>
        <div style={card}><span style={cl}>Auto SKU</span><span style={cv}>{a.autoGeneratedSKU}</span></div>
        <div style={card}><span style={cl}>Primary Pkg</span><span style={cv}>{a.primaryPackaging}</span></div>
        <div style={card}><span style={cl}>Master Cartons</span><span style={cv}>{a.masterCartons}</span></div>
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(320px, 1fr))', gap: 16 }}>
        <div style={{ padding: 16, borderRadius: 'var(--radius-md)', border: '1px solid var(--color-border)', background: 'var(--color-bg-surface-default)' }}>
          <div style={{ fontSize: 'var(--text-h5)', fontWeight: 600, color: 'var(--color-text-primary)', marginBottom: 12 }}>Status Distribution</div>
          {a.statusDistribution.map((s) => {
            const pct = a.totalVariants > 0 ? Math.round((s.count / a.totalVariants) * 100) : 0;
            return (
              <div key={s.status} style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 6 }}>
                <span style={{ fontSize: 'var(--text-body-xs)', color: 'var(--color-text-secondary)', minWidth: 70 }}>{s.status}</span>
                <div style={{ flex: 1, height: 20, borderRadius: 'var(--radius-xs)', background: 'var(--color-bg-surface-raised)', overflow: 'hidden' }}>
                  <div style={{ height: '100%', width: `${pct}%`, borderRadius: 'var(--radius-xs)', background: s.color, transition: 'width 0.3s' }} />
                </div>
                <span style={{ fontSize: 'var(--text-body-xs)', color: 'var(--color-text-secondary)', minWidth: 30, textAlign: 'right' }}>{s.count}</span>
              </div>
            );
          })}
        </div>

        <div style={{ padding: 16, borderRadius: 'var(--radius-md)', border: '1px solid var(--color-border)', background: 'var(--color-bg-surface-default)' }}>
          <div style={{ fontSize: 'var(--text-h5)', fontWeight: 600, color: 'var(--color-text-primary)', marginBottom: 12 }}>Variant Groups</div>
          {a.groupDistribution.map((g) => (
            <div key={g.name} style={{ display: 'flex', justifyContent: 'space-between', padding: '6px 0', borderBottom: '1px solid var(--color-border)', fontSize: 'var(--text-body-xs)' }}>
              <span style={{ color: 'var(--color-text-primary)' }}>{g.name}</span>
              <span style={{ fontWeight: 600, color: 'var(--color-accent-blue)' }}>{g.count} variants</span>
            </div>
          ))}
        </div>

        <div style={{ padding: 16, borderRadius: 'var(--radius-md)', border: '1px solid var(--color-border)', background: 'var(--color-bg-surface-default)' }}>
          <div style={{ fontSize: 'var(--text-h5)', fontWeight: 600, color: 'var(--color-text-primary)', marginBottom: 12 }}>Recent Activity</div>
          {MOCK_VARIANT_ACTIVITY.slice(0, 8).map((ev) => (
            <div key={ev.id} style={{ display: 'flex', gap: 10, padding: '6px 0', borderBottom: '1px solid var(--color-border)' }}>
              <span style={{ fontSize: 14, opacity: 0.5 }} aria-hidden="true">
                {ev.icon === 'layers' && '🧩'}{ev.icon === 'edit' && '✏️'}{ev.icon === 'tag' && '🏷️'}
                {ev.icon === 'list' && '📋'}{ev.icon === 'box' && '📦'}{ev.icon === 'archive' && '📁'}
                {ev.icon === 'multiple' && '📑'}{ev.icon === 'copy' && '📋'}
              </span>
              <div style={{ flex: 1 }}>
                <div style={{ fontSize: 'var(--text-body-xs)', color: 'var(--color-text-primary)' }}>{ev.message}</div>
                <div style={{ fontSize: 'var(--text-body-xs)', color: 'var(--color-text-tertiary)' }}>{ev.user} · {new Date(ev.timestamp).toLocaleDateString()}</div>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
});
