package com.sporekart.ai.risk.domain;

public enum TrustFactor {
    PROVIDER_RELIABILITY,
    KNOWLEDGE_QUALITY,
    SEMANTIC_CONFIDENCE,
    PROMPT_VALIDATION,
    HISTORICAL_ACCURACY,
    POLICY_COMPLIANCE,
    WORKFLOW_SUCCESS,
    CONTEXT_COMPLETENESS,
    OUTPUT_VALIDATION
}
