version: "3.9"
services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: sporekart
      POSTGRES_USER: sporekart
      POSTGRES_PASSWORD: sporekart
    ports:
      - "5432:5432"
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
  opensearch:
    image: opensearchproject/opensearch:2.11.0
    environment:
      discovery.type: single-node
    ports:
      - "9200:9200"
