export interface ProductVariant {
  id: string;
  name: string;
  sku: string;
  productId: string;
  productName: string;
  parentId?: string;
  attributes: VariantAttribute[];
  packaging?: PackagingInfo;
  specifications?: Specification[];
  status: VariantStatus;
  isDefault: boolean;
  priority: number;
  notes?: string;
  barcode?: string;
  qrCode?: string;
  price: number;
  stock: number;
  createdAt: string;
  updatedAt: string;
}

export type VariantStatus = 'active' | 'inactive' | 'draft' | 'archived';

export interface VariantAttribute {
  id: string;
  name: string;
  value: string;
  type: AttributeType;
  group?: string;
  displayOrder: number;
}

export type AttributeType =
  | 'text'
  | 'number'
  | 'select'
  | 'boolean'
  | 'date'
  | 'dimension'
  | 'weight';

export interface AttributeDefinition {
  id: string;
  name: string;
  label: string;
  type: AttributeType;
  group: AttributeGroup;
  options?: string[];
  required: boolean;
  filterable: boolean;
  comparable: boolean;
  displayOrder: number;
  description?: string;
}

export type AttributeGroup =
  | 'general'
  | 'technical'
  | 'agriculture'
  | 'storage'
  | 'usage'
  | 'safety'
  | 'compliance'
  | 'marketing'
  | 'packaging';

export const ATTRIBUTE_GROUP_LABELS: Record<AttributeGroup, string> = {
  general: 'General',
  technical: 'Technical',
  agriculture: 'Agriculture',
  storage: 'Storage',
  usage: 'Usage',
  safety: 'Safety',
  compliance: 'Compliance',
  marketing: 'Marketing',
  packaging: 'Packaging',
};

export interface PackagingInfo {
  id: string;
  name: string;
  type: PackagingType;
  weight: number;
  weightUnit: 'g' | 'kg' | 'lb';
  length: number;
  width: number;
  height: number;
  dimensionUnit: 'cm' | 'in' | 'mm';
  volume?: number;
  volumeUnit?: 'L' | 'ml' | 'cu_cm';
  material?: string;
  storageInstructions?: string;
  handlingInstructions?: string;
  expiryDate?: string;
  manufacturingDate?: string;
  isPrimary: boolean;
  isMasterCarton: boolean;
  status: 'active' | 'inactive';
}

export type PackagingType = 'pouch' | 'bag' | 'box' | 'tray' | 'jar' | 'bottle' | 'carton' | 'crate' | 'bundle' | 'other';

export interface Specification {
  id: string;
  name: string;
  value: string;
  group: AttributeGroup;
  displayOrder: number;
}

export interface SKUEntry {
  id: string;
  sku: string;
  variantId?: string;
  variantName: string;
  productId: string;
  productName: string;
  prefix?: string;
  suffix?: string;
  autoGenerated: boolean;
  reserved: boolean;
  duplicate: boolean;
  status: 'active' | 'inactive' | 'reserved';
  createdAt: string;
}

export interface BarcodeEntry {
  id: string;
  sku: string;
  variantId?: string;
  barcode?: string;
  qrCode?: string;
  type: 'ean13' | 'upc' | 'code128' | 'qr';
  status: 'generated' | 'pending' | 'failed';
  downloadUrl?: string;
  printUrl?: string;
}

export interface VariantGroup {
  id: string;
  name: string;
  description?: string;
  parentId?: string;
  variants: string[];
  attributes: string[];
  status: 'active' | 'inactive';
}

export type VariantSectionId =
  | 'overview'
  | 'variants'
  | 'attributes'
  | 'sku'
  | 'packaging'
  | 'specifications'
  | 'configurations'
  | 'bulk-operations'
  | 'preview'
  | 'settings'
  | 'help';

export const VARIANT_SECTION_LABELS: Record<VariantSectionId, string> = {
  overview: 'Overview',
  variants: 'Variants',
  attributes: 'Attributes',
  sku: 'SKU Management',
  packaging: 'Packaging',
  specifications: 'Specifications',
  configurations: 'Configurations',
  'bulk-operations': 'Bulk Operations',
  preview: 'Preview',
  settings: 'Settings',
  help: 'Help',
};

export const VARIANT_SECTION_ICONS: Record<VariantSectionId, string> = {
  overview: 'dashboard',
  variants: 'layers',
  attributes: 'list',
  sku: 'tag',
  packaging: 'box',
  specifications: 'file-text',
  configurations: 'settings',
  'bulk-operations': 'multiple',
  preview: 'eye',
  settings: 'gear',
  help: 'help',
};

export type VariantRole = 'viewer' | 'editor' | 'manager' | 'administrator';

export const VARIANT_ROLE_HIERARCHY: VariantRole[] = ['viewer', 'editor', 'manager', 'administrator'];

export const CURRENT_VARIANT_ROLE: VariantRole = 'manager';

export const VARIANT_PERMISSIONS: Record<VariantRole, string[]> = {
  viewer: ['view'],
  editor: ['view', 'create', 'edit'],
  manager: ['view', 'create', 'edit', 'delete', 'duplicate', 'archive', 'restore'],
  administrator: ['view', 'create', 'edit', 'delete', 'duplicate', 'archive', 'restore', 'bulk_operations'],
};

export interface VariantFilters {
  search: string;
  variantType: ('single' | 'multiple')[];
  attributes: string[];
  packaging: string[];
  status: VariantStatus[];
  category: string[];
  brand: string[];
  recentlyUpdated: boolean;
  recentlyCreated: boolean;
  archived: boolean;
  featured: boolean;
  savedFilters: VariantSavedFilter[];
  activeSavedFilter?: string;
}

export interface VariantSavedFilter {
  id: string;
  name: string;
  filters: Partial<VariantFilters>;
}

export const EMPTY_VARIANT_FILTERS: VariantFilters = {
  search: '',
  variantType: [],
  attributes: [],
  packaging: [],
  status: [],
  category: [],
  brand: [],
  recentlyUpdated: false,
  recentlyCreated: false,
  archived: false,
  featured: false,
  savedFilters: [],
};

export type VariantSortOption = 'name' | 'sku' | 'weight' | 'package' | 'updated' | 'created' | 'status' | 'alphabetical';

export interface BulkVariantOperation {
  id: string;
  name: string;
  type: BulkVariantOpType;
  description: string;
  icon: string;
}

export type BulkVariantOpType =
  | 'create_variants'
  | 'delete_variants'
  | 'duplicate_variants'
  | 'assign_packaging'
  | 'assign_attributes'
  | 'generate_sku'
  | 'export'
  | 'archive'
  | 'restore';
