package com.sporekart.ai.assistant.domain;

public enum AssistantType {
    CUSTOMER_COPILOT,
    PRODUCT_COPILOT,
    TRAINING_COPILOT,
    GROWER_COPILOT,
    MARKETPLACE_COPILOT,
    ERP_COPILOT,
    INVENTORY_COPILOT,
    ORDER_COPILOT,
    ANALYTICS_COPILOT,
    SUPPORT_COPILOT,
    ADMINISTRATION_COPILOT,
    NOTIFICATION_COPILOT
}
