package com.sporekart.ai.prompt.domain;

public enum AuditAction {
    TEMPLATE_CREATED,
    TEMPLATE_UPDATED,
    TEMPLATE_DELETED,
    VERSION_CREATED,
    VERSION_PUBLISHED,
    VERSION_DEPRECATED,
    VERSION_ARCHIVED,
    VERSION_ROLLED_BACK,
    STATUS_CHANGED,
    CATEGORY_CREATED,
    CATEGORY_UPDATED,
    CATEGORY_DELETED,
    VARIABLE_ADDED,
    VARIABLE_UPDATED,
    VARIABLE_REMOVED,
    PROMPT_RENDERED,
    PROMPT_EXECUTED,
    IMPORT_EXPORT
}
