export interface TokenEntry {
  id: string;
  name: string;
  value: string;
  category: 'color' | 'typography' | 'spacing' | 'radius' | 'elevation' | 'animation';
  type: 'primitive' | 'semantic';
  usage: number;
  deprecated: boolean;
  replacement?: string;
  examples: string[];
}

export const tokenManifest: TokenEntry[] = [
  // ── COLOR (Primitive) ──
  { id: 'color-green-50', name: '--color-green-50', value: '#E8F5E9', category: 'color', type: 'primitive', usage: 12, deprecated: false, examples: ['Lightest green background'] },
  { id: 'color-green-100', name: '--color-green-100', value: '#C8E6C9', category: 'color', type: 'primitive', usage: 8, deprecated: false, examples: ['Weak border'] },
  { id: 'color-green-200', name: '--color-green-200', value: '#A5D6A7', category: 'color', type: 'primitive', usage: 5, deprecated: false, examples: ['Disabled background'] },
  { id: 'color-green-300', name: '--color-green-300', value: '#81C784', category: 'color', type: 'primitive', usage: 7, deprecated: false, examples: ['Success accent'] },
  { id: 'color-green-400', name: '--color-green-400', value: '#66BB6A', category: 'color', type: 'primitive', usage: 15, deprecated: false, examples: ['Interactive hover'] },
  { id: 'color-green-500', name: '--color-green-500', value: '#4CAF50', category: 'color', type: 'primitive', usage: 20, deprecated: false, examples: ['Secondary action'] },
  { id: 'color-green-600', name: '--color-green-600', value: '#2F6F4F', category: 'color', type: 'primitive', usage: 42, deprecated: false, examples: ['Primary brand color'] },
  { id: 'color-green-700', name: '--color-green-700', value: '#265D3F', category: 'color', type: 'primitive', usage: 18, deprecated: false, examples: ['Primary hover'] },
  { id: 'color-green-800', name: '--color-green-800', value: '#1E4D33', category: 'color', type: 'primitive', usage: 10, deprecated: false, examples: ['Primary pressed'] },
  { id: 'color-green-900', name: '--color-green-900', value: '#153A26', category: 'color', type: 'primitive', usage: 25, deprecated: false, examples: ['High-emphasis text'] },
  { id: 'color-green-950', name: '--color-green-950', value: '#0A2516', category: 'color', type: 'primitive', usage: 3, deprecated: false, examples: ['Deepest green'] },
  { id: 'color-neutral-50', name: '--color-neutral-50', value: '#FAFAFA', category: 'color', type: 'primitive', usage: 30, deprecated: false, examples: ['Near white background'] },
  { id: 'color-neutral-100', name: '--color-neutral-100', value: '#F7F8F7', category: 'color', type: 'primitive', usage: 45, deprecated: false, examples: ['Page background'] },
  { id: 'color-neutral-200', name: '--color-neutral-200', value: '#E3E6E3', category: 'color', type: 'primitive', usage: 38, deprecated: false, examples: ['Borders, dividers'] },
  { id: 'color-neutral-300', name: '--color-neutral-300', value: '#CFCFCF', category: 'color', type: 'primitive', usage: 12, deprecated: false, examples: ['Disabled border'] },
  { id: 'color-neutral-400', name: '--color-neutral-400', value: '#A8A8A8', category: 'color', type: 'primitive', usage: 20, deprecated: false, examples: ['Placeholder icon'] },
  { id: 'color-neutral-500', name: '--color-neutral-500', value: '#8C8C8C', category: 'color', type: 'primitive', usage: 15, deprecated: false, examples: ['Secondary text'] },
  { id: 'color-neutral-600', name: '--color-neutral-600', value: '#6D6D6D', category: 'color', type: 'primitive', usage: 22, deprecated: false, examples: ['Text secondary'] },
  { id: 'color-neutral-700', name: '--color-neutral-700', value: '#4D4D4D', category: 'color', type: 'primitive', usage: 8, deprecated: false, examples: ['Medium emphasis'] },
  { id: 'color-neutral-800', name: '--color-neutral-800', value: '#2D2D2D', category: 'color', type: 'primitive', usage: 10, deprecated: false, examples: ['Dark surface'] },
  { id: 'color-neutral-900', name: '--color-neutral-900', value: '#1D2B22', category: 'color', type: 'primitive', usage: 50, deprecated: false, examples: ['Text primary'] },
  { id: 'color-neutral-950', name: '--color-neutral-950', value: '#0D140E', category: 'color', type: 'primitive', usage: 5, deprecated: false, examples: ['Deepest neutral'] },
  { id: 'color-danger-50', name: '--color-danger-50', value: '#FBE9E7', category: 'color', type: 'primitive', usage: 6, deprecated: false, examples: ['Error background'] },
  { id: 'color-danger-500', name: '--color-danger-500', value: '#EF5350', category: 'color', type: 'primitive', usage: 25, deprecated: false, examples: ['Destructive action'] },
  { id: 'color-danger-600', name: '--color-danger-600', value: '#C62828', category: 'color', type: 'primitive', usage: 18, deprecated: false, examples: ['Error text'] },
  { id: 'color-warning-50', name: '--color-warning-50', value: '#FFF8E1', category: 'color', type: 'primitive', usage: 5, deprecated: false, examples: ['Warning background'] },
  { id: 'color-warning-500', name: '--color-warning-500', value: '#FFB300', category: 'color', type: 'primitive', usage: 15, deprecated: false, examples: ['Warning accent'] },
  { id: 'color-warning-600', name: '--color-warning-600', value: '#F57F17', category: 'color', type: 'primitive', usage: 10, deprecated: false, examples: ['Warning text'] },
  { id: 'color-info-50', name: '--color-info-50', value: '#E3F2FD', category: 'color', type: 'primitive', usage: 4, deprecated: false, examples: ['Info background'] },
  { id: 'color-info-500', name: '--color-info-500', value: '#2196F3', category: 'color', type: 'primitive', usage: 12, deprecated: false, examples: ['Info accent'] },
  { id: 'color-info-600', name: '--color-info-600', value: '#1565C0', category: 'color', type: 'primitive', usage: 8, deprecated: false, examples: ['Info text'] },
  { id: 'color-success-50', name: '--color-success-50', value: '#E8F5E9', category: 'color', type: 'primitive', usage: 6, deprecated: false, examples: ['Success background'] },
  { id: 'color-success-500', name: '--color-success-500', value: '#4CAF50', category: 'color', type: 'primitive', usage: 14, deprecated: false, examples: ['Success accent'] },
  { id: 'color-success-600', name: '--color-success-600', value: '#2E7D32', category: 'color', type: 'primitive', usage: 10, deprecated: false, examples: ['Success text'] },
  // ── COLOR (Semantic) ──
  { id: 'color-bg-primary', name: '--color-bg-primary-default', value: '#2F6F4F', category: 'color', type: 'semantic', usage: 65, deprecated: false, examples: ['Primary button', 'Active nav'] },
  { id: 'color-bg-primary-hover', name: '--color-bg-primary-hover', value: '#265D3F', category: 'color', type: 'semantic', usage: 42, deprecated: false, examples: ['Button hover'] },
  { id: 'color-bg-primary-pressed', name: '--color-bg-primary-pressed', value: '#1E4D33', category: 'color', type: 'semantic', usage: 20, deprecated: false, examples: ['Button pressed'] },
  { id: 'color-bg-surface', name: '--color-bg-surface-default', value: '#FFFFFF', category: 'color', type: 'semantic', usage: 60, deprecated: false, examples: ['Card background', 'Dropdown'] },
  { id: 'color-bg-page', name: '--color-bg-page', value: '#F7F8F7', category: 'color', type: 'semantic', usage: 55, deprecated: false, examples: ['Page background'] },
  { id: 'color-bg-danger', name: '--color-bg-danger-default', value: '#EF5350', category: 'color', type: 'semantic', usage: 15, deprecated: false, examples: ['Destructive button'] },
  { id: 'color-bg-disabled', name: '--color-bg-disabled', value: '#E3E6E3', category: 'color', type: 'semantic', usage: 30, deprecated: false, examples: ['Disabled input'] },
  { id: 'color-text-primary', name: '--color-text-primary', value: '#1D2B22', category: 'color', type: 'semantic', usage: 80, deprecated: false, examples: ['Body text', 'Headings'] },
  { id: 'color-text-secondary', name: '--color-text-secondary', value: '#6D6D6D', category: 'color', type: 'semantic', usage: 55, deprecated: false, examples: ['Caption', 'Helper text'] },
  { id: 'color-text-disabled', name: '--color-text-disabled', value: '#A8A8A8', category: 'color', type: 'semantic', usage: 25, deprecated: false, examples: ['Disabled label'] },
  { id: 'color-text-link', name: '--color-text-link', value: '#2F6F4F', category: 'color', type: 'semantic', usage: 18, deprecated: false, examples: ['Hyperlink text'] },
  { id: 'color-text-danger', name: '--color-text-danger', value: '#C62828', category: 'color', type: 'semantic', usage: 22, deprecated: false, examples: ['Error message'] },
  { id: 'color-border-default', name: '--color-border-default', value: '#E3E6E3', category: 'color', type: 'semantic', usage: 48, deprecated: false, examples: ['Input border', 'Divider'] },
  { id: 'color-border-hover', name: '--color-border-hover', value: '#A5D6A7', category: 'color', type: 'semantic', usage: 25, deprecated: false, examples: ['Input hover border'] },
  { id: 'color-border-focus', name: '--color-border-focus', value: '#2F6F4F', category: 'color', type: 'semantic', usage: 30, deprecated: false, examples: ['Focus ring'] },
  { id: 'color-border-danger', name: '--color-border-danger', value: '#EF5350', category: 'color', type: 'semantic', usage: 12, deprecated: false, examples: ['Error border'] },
  { id: 'color-dataViz-1', name: '--color-dataviz-categorical-1', value: '#2F6F4F', category: 'color', type: 'semantic', usage: 8, deprecated: false, examples: ['Chart series 1'] },
  { id: 'color-dataViz-2', name: '--color-dataviz-categorical-2', value: '#1565C0', category: 'color', type: 'semantic', usage: 7, deprecated: false, examples: ['Chart series 2'] },
  { id: 'color-dataViz-3', name: '--color-dataviz-categorical-3', value: '#F57F17', category: 'color', type: 'semantic', usage: 6, deprecated: false, examples: ['Chart series 3'] },
  { id: 'color-dataViz-4', name: '--color-dataviz-categorical-4', value: '#C62828', category: 'color', type: 'semantic', usage: 5, deprecated: false, examples: ['Chart series 4'] },
  // ── TYPOGRAPHY (Primitive) ──
  { id: 'font-size-xs', name: '--font-size-xs', value: '0.75rem (12px)', category: 'typography', type: 'primitive', usage: 25, deprecated: false, examples: ['Caption text'] },
  { id: 'font-size-sm', name: '--font-size-sm', value: '0.875rem (14px)', category: 'typography', type: 'primitive', usage: 40, deprecated: false, examples: ['Small body text'] },
  { id: 'font-size-base', name: '--font-size-base', value: '1rem (16px)', category: 'typography', type: 'primitive', usage: 65, deprecated: false, examples: ['Body text', 'Paragraph'] },
  { id: 'font-size-lg', name: '--font-size-lg', value: '1.125rem (18px)', category: 'typography', type: 'primitive', usage: 30, deprecated: false, examples: ['Large body text'] },
  { id: 'font-size-xl', name: '--font-size-xl', value: '1.25rem (20px)', category: 'typography', type: 'primitive', usage: 22, deprecated: false, examples: ['Subheading'] },
  { id: 'font-size-2xl', name: '--font-size-2xl', value: '1.5rem (24px)', category: 'typography', type: 'primitive', usage: 18, deprecated: false, examples: ['H3 heading'] },
  { id: 'font-size-3xl', name: '--font-size-3xl', value: '1.875rem (30px)', category: 'typography', type: 'primitive', usage: 12, deprecated: false, examples: ['H2 heading'] },
  { id: 'font-size-4xl', name: '--font-size-4xl', value: '2.25rem (36px)', category: 'typography', type: 'primitive', usage: 8, deprecated: false, examples: ['H1 heading'] },
  { id: 'font-weight-regular', name: '--font-weight-regular', value: '400', category: 'typography', type: 'primitive', usage: 60, deprecated: false, examples: ['Body text'] },
  { id: 'font-weight-medium', name: '--font-weight-medium', value: '500', category: 'typography', type: 'primitive', usage: 35, deprecated: false, examples: ['Button label'] },
  { id: 'font-weight-semibold', name: '--font-weight-semibold', value: '600', category: 'typography', type: 'primitive', usage: 40, deprecated: false, examples: ['Section heading'] },
  { id: 'font-weight-bold', name: '--font-weight-bold', value: '700', category: 'typography', type: 'primitive', usage: 25, deprecated: false, examples: ['Page title'] },
  { id: 'line-height-xs', name: '--line-height-xs', value: '1', category: 'typography', type: 'primitive', usage: 10, deprecated: false, examples: ['Tight heading'] },
  { id: 'line-height-sm', name: '--line-height-sm', value: '1.25', category: 'typography', type: 'primitive', usage: 20, deprecated: false, examples: ['Compact text'] },
  { id: 'line-height-md', name: '--line-height-md', value: '1.5', category: 'typography', type: 'primitive', usage: 50, deprecated: false, examples: ['Body text'] },
  { id: 'line-height-lg', name: '--line-height-lg', value: '1.75', category: 'typography', type: 'primitive', usage: 15, deprecated: false, examples: ['Readable paragraph'] },
  { id: 'letter-spacing-tight', name: '--letter-spacing-tight', value: '-0.025em', category: 'typography', type: 'primitive', usage: 8, deprecated: false, examples: ['Heading spacing'] },
  { id: 'letter-spacing-normal', name: '--letter-spacing-normal', value: '0', category: 'typography', type: 'primitive', usage: 60, deprecated: false, examples: ['Default spacing'] },
  { id: 'letter-spacing-wide', name: '--letter-spacing-wide', value: '0.05em', category: 'typography', type: 'primitive', usage: 5, deprecated: false, examples: ['Uppercase label'] },
  // ── TYPOGRAPHY (Semantic) ──
  { id: 'text-h1', name: '--text-h1', value: '2.25rem/1.1 700', category: 'typography', type: 'semantic', usage: 15, deprecated: false, examples: ['Page heading'] },
  { id: 'text-h2', name: '--text-h2', value: '1.875rem/1.2 600', category: 'typography', type: 'semantic', usage: 18, deprecated: false, examples: ['Section heading'] },
  { id: 'text-h3', name: '--text-h3', value: '1.5rem/1.3 600', category: 'typography', type: 'semantic', usage: 22, deprecated: false, examples: ['Card title'] },
  { id: 'text-body', name: '--text-body', value: '1rem/1.5 400', category: 'typography', type: 'semantic', usage: 70, deprecated: false, examples: ['Paragraph text'] },
  { id: 'text-body-sm', name: '--text-body-sm', value: '0.875rem/1.5 400', category: 'typography', type: 'semantic', usage: 35, deprecated: false, examples: ['Small paragraph'] },
  { id: 'text-caption', name: '--text-caption', value: '0.75rem/1.4 400', category: 'typography', type: 'semantic', usage: 28, deprecated: false, examples: ['Helper text', 'Label'] },
  { id: 'text-button', name: '--text-button', value: '0.875rem/1 500', category: 'typography', type: 'semantic', usage: 45, deprecated: false, examples: ['Button label'] },
  { id: 'text-label', name: '--text-label', value: '0.875rem/1.25 500', category: 'typography', type: 'semantic', usage: 30, deprecated: false, examples: ['Form label'] },
  { id: 'text-overline', name: '--text-overline', value: '0.75rem/1 600 0.05em', category: 'typography', type: 'semantic', usage: 8, deprecated: false, examples: ['Section overline'] },
  // ── SPACING (Primitive) ──
  { id: 'spacing-3xs', name: '--spacing-3xs', value: '2px', category: 'spacing', type: 'primitive', usage: 15, deprecated: false, examples: ['Tight gap'] },
  { id: 'spacing-2xs', name: '--spacing-2xs', value: '4px', category: 'spacing', type: 'primitive', usage: 30, deprecated: false, examples: ['Icon spacing'] },
  { id: 'spacing-xs', name: '--spacing-xs', value: '8px', category: 'spacing', type: 'primitive', usage: 55, deprecated: false, examples: ['Element gap'] },
  { id: 'spacing-sm', name: '--spacing-sm', value: '12px', category: 'spacing', type: 'primitive', usage: 40, deprecated: false, examples: ['Small padding'] },
  { id: 'spacing-md', name: '--spacing-md', value: '16px', category: 'spacing', type: 'primitive', usage: 75, deprecated: false, examples: ['Standard padding'] },
  { id: 'spacing-lg', name: '--spacing-lg', value: '24px', category: 'spacing', type: 'primitive', usage: 60, deprecated: false, examples: ['Section gap'] },
  { id: 'spacing-xl', name: '--spacing-xl', value: '32px', category: 'spacing', type: 'primitive', usage: 35, deprecated: false, examples: ['Card margin'] },
  { id: 'spacing-2xl', name: '--spacing-2xl', value: '48px', category: 'spacing', type: 'primitive', usage: 20, deprecated: false, examples: ['Page section'] },
  { id: 'spacing-3xl', name: '--spacing-3xl', value: '64px', category: 'spacing', type: 'primitive', usage: 12, deprecated: false, examples: ['Page padding'] },
  // ── SPACING (Semantic) ──
  { id: 'space-stack-xs', name: '--space-stack-xs', value: 'var(--spacing-xs)', category: 'spacing', type: 'semantic', usage: 30, deprecated: false, examples: ['Tight stack'] },
  { id: 'space-stack-sm', name: '--space-stack-sm', value: 'var(--spacing-sm)', category: 'spacing', type: 'semantic', usage: 35, deprecated: false, examples: ['Close stack'] },
  { id: 'space-stack-md', name: '--space-stack-md', value: 'var(--spacing-md)', category: 'spacing', type: 'semantic', usage: 55, deprecated: false, examples: ['Standard stack'] },
  { id: 'space-stack-lg', name: '--space-stack-lg', value: 'var(--spacing-lg)', category: 'spacing', type: 'semantic', usage: 45, deprecated: false, examples: ['Section stack'] },
  { id: 'space-inline-xs', name: '--space-inline-xs', value: 'var(--spacing-xs)', category: 'spacing', type: 'semantic', usage: 25, deprecated: false, examples: ['Tight inline'] },
  { id: 'space-inline-sm', name: '--space-inline-sm', value: 'var(--spacing-sm)', category: 'spacing', type: 'semantic', usage: 30, deprecated: false, examples: ['Close inline'] },
  { id: 'space-inline-md', name: '--space-inline-md', value: 'var(--spacing-md)', category: 'spacing', type: 'semantic', usage: 50, deprecated: false, examples: ['Standard inline'] },
  { id: 'space-page-x', name: '--space-page-x', value: 'var(--spacing-2xl)', category: 'spacing', type: 'semantic', usage: 22, deprecated: false, examples: ['Page horizontal padding'] },
  { id: 'space-page-y', name: '--space-page-y', value: 'var(--spacing-3xl)', category: 'spacing', type: 'semantic', usage: 18, deprecated: false, examples: ['Page vertical padding'] },
  { id: 'space-section-gap', name: '--space-section-gap', value: 'var(--spacing-2xl)', category: 'spacing', type: 'semantic', usage: 25, deprecated: false, examples: ['Between sections'] },
  { id: 'space-card-padding', name: '--space-card-padding', value: 'var(--spacing-lg)', category: 'spacing', type: 'semantic', usage: 35, deprecated: false, examples: ['Card inner padding'] },
  // ── RADIUS (Primitive) ──
  { id: 'radius-none', name: '--radius-none', value: '0', category: 'radius', type: 'primitive', usage: 5, deprecated: false, examples: ['Sharp edges'] },
  { id: 'radius-sm', name: '--radius-sm', value: '4px', category: 'radius', type: 'primitive', usage: 40, deprecated: false, examples: ['Small elements'] },
  { id: 'radius-md', name: '--radius-md', value: '6px', category: 'radius', type: 'primitive', usage: 55, deprecated: false, examples: ['Input fields'] },
  { id: 'radius-lg', name: '--radius-lg', value: '8px', category: 'radius', type: 'primitive', usage: 45, deprecated: false, examples: ['Card corners'] },
  { id: 'radius-xl', name: '--radius-xl', value: '12px', category: 'radius', type: 'primitive', usage: 25, deprecated: false, examples: ['Modal corners'] },
  { id: 'radius-2xl', name: '--radius-2xl', value: '16px', category: 'radius', type: 'primitive', usage: 10, deprecated: false, examples: ['Sheet corners'] },
  { id: 'radius-full', name: '--radius-full', value: '9999px', category: 'radius', type: 'primitive', usage: 20, deprecated: false, examples: ['Pill shape', 'Avatar'] },
  // ── RADIUS (Semantic) ──
  { id: 'radius-input', name: '--radius-input', value: 'var(--radius-sm)', category: 'radius', type: 'semantic', usage: 42, deprecated: false, examples: ['Input fields'] },
  { id: 'radius-card', name: '--radius-card', value: 'var(--radius-lg)', category: 'radius', type: 'semantic', usage: 38, deprecated: false, examples: ['Card component'] },
  { id: 'radius-button', name: '--radius-button', value: 'var(--radius-sm)', category: 'radius', type: 'semantic', usage: 45, deprecated: false, examples: ['Button'] },
  { id: 'radius-modal', name: '--radius-modal', value: 'var(--radius-xl)', category: 'radius', type: 'semantic', usage: 15, deprecated: false, examples: ['Dialog modal'] },
  { id: 'radius-pill', name: '--radius-pill', value: 'var(--radius-full)', category: 'radius', type: 'semantic', usage: 20, deprecated: false, examples: ['Badge', 'Chip'] },
  { id: 'radius-badge', name: '--radius-badge', value: 'var(--radius-full)', category: 'radius', type: 'semantic', usage: 12, deprecated: false, examples: ['Status badge'] },
  // ── ELEVATION (Primitive) ──
  { id: 'elevation-1', name: '--elevation-1', value: '0 1px 2px rgba(29,43,34,0.08)', category: 'elevation', type: 'primitive', usage: 30, deprecated: false, examples: ['Subtle card shadow'] },
  { id: 'elevation-2', name: '--elevation-2', value: '0 1px 3px rgba(29,43,34,0.1), 0 1px 2px rgba(29,43,34,0.06)', category: 'elevation', type: 'primitive', usage: 35, deprecated: false, examples: ['Raised card'] },
  { id: 'elevation-3', name: '--elevation-3', value: '0 4px 6px rgba(29,43,34,0.1), 0 2px 4px rgba(29,43,34,0.06)', category: 'elevation', type: 'primitive', usage: 25, deprecated: false, examples: ['Dropdown menu'] },
  { id: 'elevation-4', name: '--elevation-4', value: '0 10px 15px rgba(29,43,34,0.1), 0 4px 6px rgba(29,43,34,0.05)', category: 'elevation', type: 'primitive', usage: 18, deprecated: false, examples: ['Modal dialog'] },
  { id: 'elevation-5', name: '--elevation-5', value: '0 20px 25px rgba(29,43,34,0.15), 0 10px 10px rgba(29,43,34,0.04)', category: 'elevation', type: 'primitive', usage: 10, deprecated: false, examples: ['Toast notification'] },
  // ── ELEVATION (Semantic) ──
  { id: 'shadow-card', name: '--shadow-card', value: 'var(--elevation-1)', category: 'elevation', type: 'semantic', usage: 45, deprecated: false, examples: ['Default card'] },
  { id: 'shadow-card-hover', name: '--shadow-card-hover', value: 'var(--elevation-2)', category: 'elevation', type: 'semantic', usage: 20, deprecated: false, examples: ['Card on hover'] },
  { id: 'shadow-dropdown', name: '--shadow-dropdown', value: 'var(--elevation-3)', category: 'elevation', type: 'semantic', usage: 25, deprecated: false, examples: ['Dropdown list'] },
  { id: 'shadow-modal', name: '--shadow-modal', value: 'var(--elevation-4)', category: 'elevation', type: 'semantic', usage: 15, deprecated: false, examples: ['Modal backdrop'] },
  { id: 'shadow-toast', name: '--shadow-toast', value: 'var(--elevation-5)', category: 'elevation', type: 'semantic', usage: 10, deprecated: false, examples: ['Toast notification'] },
  { id: 'shadow-tooltip', name: '--shadow-tooltip', value: 'var(--elevation-3)', category: 'elevation', type: 'semantic', usage: 12, deprecated: false, examples: ['Tooltip popup'] },
  // ── ANIMATION (Primitive) ──
  { id: 'duration-instant', name: '--duration-instant', value: '0ms', category: 'animation', type: 'primitive', usage: 5, deprecated: false, examples: ['No animation'] },
  { id: 'duration-fast', name: '--duration-fast', value: '100ms', category: 'animation', type: 'primitive', usage: 25, deprecated: false, examples: ['Hover transition'] },
  { id: 'duration-normal', name: '--duration-normal', value: '200ms', category: 'animation', type: 'primitive', usage: 45, deprecated: false, examples: ['Standard transition'] },
  { id: 'duration-slow', name: '--duration-slow', value: '400ms', category: 'animation', type: 'primitive', usage: 20, deprecated: false, examples: ['Modal enter/exit'] },
  { id: 'duration-skeleton', name: '--duration-skeleton', value: '1500ms', category: 'animation', type: 'primitive', usage: 8, deprecated: false, examples: ['Skeleton pulse'] },
  { id: 'easing-standard', name: '--easing-standard', value: 'cubic-bezier(0.4, 0, 0.2, 1)', category: 'animation', type: 'primitive', usage: 50, deprecated: false, examples: ['Standard motion'] },
  { id: 'easing-decelerate', name: '--easing-decelerate', value: 'cubic-bezier(0.0, 0, 0.2, 1)', category: 'animation', type: 'primitive', usage: 15, deprecated: false, examples: ['Enter animation'] },
  { id: 'easing-accelerate', name: '--easing-accelerate', value: 'cubic-bezier(0.4, 0, 1, 1)', category: 'animation', type: 'primitive', usage: 10, deprecated: false, examples: ['Exit animation'] },
  { id: 'easing-sharp', name: '--easing-sharp', value: 'cubic-bezier(0.4, 0, 0.6, 1)', category: 'animation', type: 'primitive', usage: 8, deprecated: false, examples: ['Snap transition'] },
  // ── ANIMATION (Semantic) ──
  { id: 'transition-fast', name: '--transition-fast', value: '100ms cubic-bezier(0.4, 0, 0.2, 1)', category: 'animation', type: 'semantic', usage: 35, deprecated: false, examples: ['Color transition'] },
  { id: 'transition-normal', name: '--transition-normal', value: '200ms cubic-bezier(0.4, 0, 0.2, 1)', category: 'animation', type: 'semantic', usage: 50, deprecated: false, examples: ['Enter/exit'] },
  { id: 'transition-slow', name: '--transition-slow', value: '400ms cubic-bezier(0.4, 0, 0.2, 1)', category: 'animation', type: 'semantic', usage: 15, deprecated: false, examples: ['Layout animation'] },
  { id: 'transition-modal', name: '--transition-modal', value: '400ms cubic-bezier(0.0, 0, 0.2, 1)', category: 'animation', type: 'semantic', usage: 12, deprecated: false, examples: ['Modal backdrop'] },
  { id: 'transition-skeleton', name: '--transition-skeleton', value: '1500ms cubic-bezier(0.4, 0, 0.6, 1) infinite', category: 'animation', type: 'semantic', usage: 8, deprecated: false, examples: ['Skeleton shimmer'] },
];
