package com.sporekart.ai.runtime.domain;

public enum AgentEventType {
    AGENT_CREATED,
    AGENT_UPDATED,
    AGENT_DELETED,
    AGENT_ACTIVATED,
    AGENT_DEACTIVATED,
    EXECUTION_STARTED,
    EXECUTION_COMPLETED,
    EXECUTION_FAILED,
    EXECUTION_TIMEOUT,
    TOOL_INVOKED,
    TOOL_COMPLETED,
    TOOL_FAILED,
    MEMORY_ACCESSED,
    SCHEDULE_TRIGGERED
}
