package com.sporekart.platform.error;

public enum ErrorCode {
    INTERNAL_ERROR,
    VALIDATION_ERROR,
    NOT_FOUND,
    DUPLICATE_RESOURCE,
    BUSINESS_RULE_VIOLATION,
    UNAUTHORIZED,
    FORBIDDEN,
    BAD_REQUEST,
    CONFLICT,
    SERVICE_UNAVAILABLE,
    EXTERNAL_SERVICE_ERROR,
    RATE_LIMIT_EXCEEDED,
    INVALID_STATE_TRANSITION,
    DEPENDENCY_FAILURE
}
